[package]
name = "scf_dos_chain"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "scf_dos_chain"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
castep-cell-fmt = { version = "0.1.0", path = "../castep-cell-io/castep_cell_fmt" }
castep-cell-io = { path = "../castep-cell-io/castep_cell_io" }
workflow_core = { path = "../../workflow_core", features = ["default-logging"] }
workflow_utils = { path = "../../workflow_utils" }
