#!/usr/bin/env python3
"""TASK-4: Add BFS unit tests for downstream_tasks: linear chain, diamond, missing start, empty start, multiple starts, cycle guard"""
import base64, json, subprocess, sys

TASK_ID = "TASK-4"
STEPS = json.loads('[{"before_b64": "ICAgICNbdGVzdF0KICAgIGZuIGluc3BlY3RfdW5rbm93bl90YXNrX2Vycm9ycygpIHsKICAgICAgICBsZXQgZGlyID0gdGVtcGZpbGU6OnRlbXBkaXIoKS51bndyYXAoKTsKICAgICAgICBsZXQgcyA9IG1ha2Vfc3RhdGUoZGlyLnBhdGgoKSk7CiAgICAgICAgYXNzZXJ0IShjbWRfaW5zcGVjdCgmcywgU29tZSgibm9uZXhpc3RlbnQiKSkuaXNfZXJyKCkpOwogICAgfQp9", "after_b64": "ICAgICNbdGVzdF0KICAgIGZuIGluc3BlY3RfdW5rbm93bl90YXNrX2Vycm9ycygpIHsKICAgICAgICBsZXQgZGlyID0gdGVtcGZpbGU6OnRlbXBkaXIoKS51bndyYXAoKTsKICAgICAgICBsZXQgcyA9IG1ha2Vfc3RhdGUoZGlyLnBhdGgoKSk7CiAgICAgICAgYXNzZXJ0IShjbWRfaW5zcGVjdCgmcywgU29tZSgibm9uZXhpc3RlbnQiKSkuaXNfZXJyKCkpOwogICAgfQoKICAgICNbdGVzdF0KICAgIGZuIGRvd25zdHJlYW1fbGluZWFyX2NoYWluKCkgewogICAgICAgIC8vIGEgLT4gYiAtPiBjOiBzdGFydCBbYV0gcmV0dXJucyB7YiwgY30KICAgICAgICBsZXQgbXV0IG1hcCA9IHN0ZDo6Y29sbGVjdGlvbnM6Okhhc2hNYXA6Om5ldygpOwogICAgICAgIG1hcC5pbnNlcnQoImEiLmludG8oKSwgdmVjIVsiYiIuaW50bygpXSk7CiAgICAgICAgbWFwLmluc2VydCgiYiIuaW50bygpLCB2ZWMhWyJjIi5pbnRvKCldKTsKICAgICAgICBtYXAuaW5zZXJ0KCJjIi5pbnRvKCksIHZlYyFbXSk7CiAgICAgICAgbGV0IHN1Y2MgPSBUYXNrU3VjY2Vzc29yczo6bmV3KG1hcCk7CiAgICAgICAgbGV0IHJlc3VsdCA9IGRvd25zdHJlYW1fdGFza3MoJlsiYSIuaW50bygpXSwgJnN1Y2MpOwogICAgICAgIGFzc2VydF9lcSEocmVzdWx0LmxlbigpLCAyKTsKICAgICAgICBhc3NlcnQhKHJlc3VsdC5jb250YWlucygiYiIpKTsKICAgICAgICBhc3NlcnQhKHJlc3VsdC5jb250YWlucygiYyIpKTsKICAgIH0KCiAgICAjW3Rlc3RdCiAgICBmbiBkb3duc3RyZWFtX2RpYW1vbmQoKSB7CiAgICAgICAgLy8gYSAtPiBiLCBhIC0+IGMsIGIgLT4gZCwgYyAtPiBkOiBzdGFydCBbYV0gcmV0dXJucyB7YiwgYywgZH0KICAgICAgICBsZXQgbXV0IG1hcCA9IHN0ZDo6Y29sbGVjdGlvbnM6Okhhc2hNYXA6Om5ldygpOwogICAgICAgIG1hcC5pbnNlcnQoImEiLmludG8oKSwgdmVjIVsiYiIuaW50bygpLCAiYyIuaW50bygpXSk7CiAgICAgICAgbWFwLmluc2VydCgiYiIuaW50bygpLCB2ZWMhWyJkIi5pbnRvKCldKTsKICAgICAgICBtYXAuaW5zZXJ0KCJjIi5pbnRvKCksIHZlYyFbImQiLmludG8oKV0pOwogICAgICAgIG1hcC5pbnNlcnQoImQiLmludG8oKSwgdmVjIVtdKTsKICAgICAgICBsZXQgc3VjYyA9IFRhc2tTdWNjZXNzb3JzOjpuZXcobWFwKTsKICAgICAgICBsZXQgcmVzdWx0ID0gZG93bnN0cmVhbV90YXNrcygmWyJhIi5pbnRvKCldLCAmc3VjYyk7CiAgICAgICAgYXNzZXJ0X2VxIShyZXN1bHQubGVuKCksIDMpOwogICAgICAgIGFzc2VydCEocmVzdWx0LmNvbnRhaW5zKCJiIikpOwogICAgICAgIGFzc2VydCEocmVzdWx0LmNvbnRhaW5zKCJjIikpOwogICAgICAgIGFzc2VydCEocmVzdWx0LmNvbnRhaW5zKCJkIikpOwogICAgfQoKICAgICNbdGVzdF0KICAgIGZuIGRvd25zdHJlYW1fc3RhcnRfbm90X2luX21hcCgpIHsKICAgICAgICBsZXQgc3VjYyA9IFRhc2tTdWNjZXNzb3JzOjpuZXcoc3RkOjpjb2xsZWN0aW9uczo6SGFzaE1hcDo6bmV3KCkpOwogICAgICAgIGxldCByZXN1bHQgPSBkb3duc3RyZWFtX3Rhc2tzKCZbIngiLmludG8oKV0sICZzdWNjKTsKICAgICAgICBhc3NlcnQhKHJlc3VsdC5pc19lbXB0eSgpKTsKICAgIH0KCiAgICAjW3Rlc3RdCiAgICBmbiBkb3duc3RyZWFtX2VtcHR5X3N0YXJ0KCkgewogICAgICAgIGxldCBtdXQgbWFwID0gc3RkOjpjb2xsZWN0aW9uczo6SGFzaE1hcDo6bmV3KCk7CiAgICAgICAgbWFwLmluc2VydCgiYSIuaW50bygpLCB2ZWMhWyJiIi5pbnRvKCldKTsKICAgICAgICBsZXQgc3VjYyA9IFRhc2tTdWNjZXNzb3JzOjpuZXcobWFwKTsKICAgICAgICBsZXQgcmVzdWx0ID0gZG93bnN0cmVhbV90YXNrcygmW10sICZzdWNjKTsKICAgICAgICBhc3NlcnQhKHJlc3VsdC5pc19lbXB0eSgpKTsKICAgIH0KCiAgICAjW3Rlc3RdCiAgICBmbiBkb3duc3RyZWFtX211bHRpcGxlX3N0YXJ0cygpIHsKICAgICAgICAvLyBhIC0+IGMsIGIgLT4gYzogc3RhcnQgW2EsIGJdIHJldHVybnMge2N9CiAgICAgICAgbGV0IG11dCBtYXAgPSBzdGQ6OmNvbGxlY3Rpb25zOjpIYXNoTWFwOjpuZXcoKTsKICAgICAgICBtYXAuaW5zZXJ0KCJhIi5pbnRvKCksIHZlYyFbImMiLmludG8oKV0pOwogICAgICAgIG1hcC5pbnNlcnQoImIiLmludG8oKSwgdmVjIVsiYyIuaW50bygpXSk7CiAgICAgICAgbWFwLmluc2VydCgiYyIuaW50bygpLCB2ZWMhW10pOwogICAgICAgIGxldCBzdWNjID0gVGFza1N1Y2Nlc3NvcnM6Om5ldyhtYXApOwogICAgICAgIGxldCByZXN1bHQgPSBkb3duc3RyZWFtX3Rhc2tzKCZbImEiLmludG8oKSwgImIiLmludG8oKV0sICZzdWNjKTsKICAgICAgICBhc3NlcnRfZXEhKHJlc3VsdC5sZW4oKSwgMSk7CiAgICAgICAgYXNzZXJ0IShyZXN1bHQuY29udGFpbnMoImMiKSk7CiAgICB9CgogICAgI1t0ZXN0XQogICAgZm4gZG93bnN0cmVhbV9jeWNsZV90ZXJtaW5hdGVzKCkgewogICAgICAgIC8vIGEgLT4gYiAtPiBhIChjeWNsZSk6IEJGUyBtdXN0IHRlcm1pbmF0ZTsgdmlzaXRlZCBzZXQgcHJldmVudHMgcmUtZW5xdWV1ZQogICAgICAgIGxldCBtdXQgbWFwID0gc3RkOjpjb2xsZWN0aW9uczo6SGFzaE1hcDo6bmV3KCk7CiAgICAgICAgbWFwLmluc2VydCgiYSIuaW50bygpLCB2ZWMhWyJiIi5pbnRvKCldKTsKICAgICAgICBtYXAuaW5zZXJ0KCJiIi5pbnRvKCksIHZlYyFbImEiLmludG8oKV0pOwogICAgICAgIGxldCBzdWNjID0gVGFza1N1Y2Nlc3NvcnM6Om5ldyhtYXApOwogICAgICAgIGxldCByZXN1bHQgPSBkb3duc3RyZWFtX3Rhc2tzKCZbImEiLmludG8oKV0sICZzdWNjKTsKICAgICAgICBhc3NlcnQhKHJlc3VsdC5jb250YWlucygiYiIpKTsKICAgICAgICBhc3NlcnQhKHJlc3VsdC5jb250YWlucygiYSIpKTsKICAgIH0KfQ==", "target": "workflow-cli/src/main.rs", "index": 0}]')

for step in STEPS:
    before = base64.b64decode(step["before_b64"]).decode()
    after = base64.b64decode(step["after_b64"]).decode()
    target = step["target"]
    idx = step["index"]

    content = open(target).read()
    if before not in content:
        print(f"FAILED {TASK_ID} change {idx}: pattern not found in {target}", file=sys.stderr)
        print(f"Expected (first 200 chars): {repr(before[:200])}", file=sys.stderr)
        sys.exit(1)

    result = subprocess.run(
        ["sd", "-F", "-A", "-n", "1", before, after, target],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"FAILED {TASK_ID} change {idx}: sd error: {result.stderr}", file=sys.stderr)
        sys.exit(result.returncode)

    new_content = open(target).read()
    if after and after not in new_content:
        print(f"FAILED {TASK_ID} change {idx}: replacement not found after apply", file=sys.stderr)
        sys.exit(1)

    print(f"OK {TASK_ID} change {idx}: applied to {target}")

print(f"OK {TASK_ID}: all changes applied")
